[variables]
NIXPACKS_PYTHON_VERSION = "3.11.9"

[phases.setup]
nixPkgs = ["python311", "nodejs_18"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "python manage.py collectstatic --noinput",
]

[start]
cmd = "python manage.py migrate && gunicorn payrollhq.wsgi:application --bind 0.0.0.0:$PORT"